version: '3.7'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - .:/Test_Case
    links:
      - db
    depends_on:
      - db
    networks:
      - backend
#  db:
#      image: mongo:5.0
#      ports:
#        - "27017:27017"
#      env_file:
#        - ./.env
#      volumes:
#        - ~/apps/mongo:/data/db
#      networks:
#        - backend

networks:
  backend:
    driver: bridge
